kind: Secret
apiVersion: v1
metadata:
  name: app-secret
  namespace: three
type: opaque
stringData:
  MONGO_CONN_STR: mongodb+srv://noor09:<aTcltBlkiP97qWls>@three-tier-cluster.mi4oczi.mongodb.net/threetier?appName=three-tier-cluster
